name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest

    
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
      - name: Change Directory
        run: |
          ls -a
          cd poc-solid-map
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install Dependencies and  build 
        run: |
          ls 
          cd poc-solid-map
          npm install
          npm install vite@latest
          npm run build
      
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_SAND_0A0FBFF03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          run : |
            ls -a
          app_location: "./dist" # Chemin vers les fichiers construits
        
  
